/**
 * 
 */
package com.vimukti.accounter.web.client.ui;

import com.google.gwt.user.client.Element;
import com.google.gwt.user.client.ui.UIObject;

/**
 * @author vimukti5
 * 
 */
public class PrintUtils {

	public static native void it() /*-{
		$wnd.print();
	}-*/;

	public static native void it(String html) /*-{
		var frame = $doc.getElementById('__printingFrame');
		if (!frame) {
			$wnd.alert("Error: Can't find printing frame.");
			return;
		}
		frame = frame.contentWindow;
		var doc = frame.document;
		doc.open();
		doc.write(html);
		doc.close();
		frame.focus();
		frame.print();
	}-*/;

	public static void print(UIObject obj) {
		if (obj == null) {
			UIUtils.say("No Data To Print...");
			return;
		}

		it("", obj.getElement().getInnerHTML());
	}

	public static void it(Element element) {
		it("", element.getInnerHTML());
	}

	// public static void it(String style, String it, String dynamicStyle) {
	// String style1 = "FinancePrint.css";
	// it("<html><head>+"
	// + dynamicStyle
	// + "<link rel='stylesheet' type='text/css' href='"
	//
	// + style1
	// +
	// "' media='print'></link></head><body><table border=0 align=\"center\" width=\"100%\"><thead><tr><th align=\"center\" width=100%><font size=\"5\" color=\"black\"><strong>"
	// + FinanceApplication.getCompany().getName()
	// .replace(
	// FinanceApplication.getCompany().getName()
	// .charAt(0)
	// + "",
	// (FinanceApplication.getCompany().getName()
	// .charAt(0) + "").toUpperCase())
	// +
	// "</strong></font></thead><tfoot><tr><td align=\"center\"  width=100%><font size=\"4\" color=\"black\"><strong>Invoice generated by Bizantra (www.bizantra.com)</strong></font></tfoot><tbody><tr><td width=\"100%\">"
	// + it + "</td></tr></tbody></table> </body></html>");
	// }

	public static void it(String style, String it) {
		String style1 = "FinancePrint.css";
		String html = "<html><head><link rel='stylesheet' type='text/css' href='"
				+ style1
				+ "' media='print'></link></head><body><table border=0 align=\"center\" width=\"100%\"><thead><tr><th align=\"center\" width=100%><font size=\"5\" color=\"black\"><strong>"
				+ Accounter
						.getCompany()
						.getName()
						.replace(
								Accounter.getCompany().getName().charAt(0) + "",
								(Accounter.getCompany().getName().charAt(0) + "")
										.toUpperCase())
				+ "</strong></font></thead><tfoot><tr><td align=\"center\"  width=100%><font size=\"4\" color=\"black\"><strong>Invoice generated by Bizantra (www.bizantra.com)</strong></font></tfoot><tbody height=\"100%\"><tr><td width=\"100%\">"
				+ it + "</td></tr></tbody></table> </body></html>";
		System.out.println(html);
		it(html);
	}

	public static void it(String style, UIObject obj) {
		if (obj == null) {
			UIUtils.say("No Data To Print...");
			return;
		}
		it(style, obj.getElement().getInnerHTML());
	}

	public static void it(String style, Element element) {
		it(style, element.getInnerHTML());
	}

}
