package com.vimukti.accounter.mobile;

public enum ActionNames {
	ADD_MORE_ITEMS, FINISH, DELETE_ITEM, ADD_MORE_CUSTOMERS, ADD_MORE_CONTACTS, ADD_MORE_ACCOUNTS, ADD_MORE_BILLS, ADD_MORE_TAX_ITEMS, ADD_MORE_LOCATIONS, FINISH_ITEM, IN_ACTIVE, ALL, ACTIVE, NEXT_PAGE, PREV_PAGE, OPEN, COMPLETED, CANCELLED, SERVICE_ITEM, PRODUCT_ITEM, ISSUED, NOT_ISSUED, VOIDED, ADD_MORE_PAYMENTS, DELETE_RECEIVE_PAYMENT, FINISH_RECEIVE_PAYMENT, FULLY_APPLIED, DELETE_PAY_BILL, FINISH_PAY_BILL, CREDIT_CARD, CASH, FULL_SETUP, PARTIAL_SETUP, FINISH_FIRST_PAGE, FINISH_COMMAND, CLOSE, SET_DEFAULT, DELETE_CONTACT,

}
