package com.vimukti.accounter.mobile;

public enum ActionNames {
	ADD_MORE_ITEMS, FINISH, DELETE_ITEM, ADD_MORE_CUSTOMERS, ADD_MORE_CONTACTS, ADD_MORE_ACCOUNTS, ADD_MORE_BILLS, ADD_MORE_TAX_ITEMS, ADD_MORE_LOCATIONS, FINISH_ITEM, IN_ACTIVE, ALL, ACTIVE, NEXT_PAGE, PREV_PAGE,

}
