package com.vimukti.accounter.mobile;

public enum RequirementType {

	STRING, INTEGER, AMOUNT, DATE, CUSTOMER, VENDOR, ACCOUNT, ITEM, TAXCODE, TAXAGENCY, TAXITEM, PAYEE, BASEREPORT, VAT_RETURN_BOX, PAYMENT_TERMS, VAT_RETURN, TAXITEM_GROUP, ITEM_GROUP, BANK_ACCOUNT, TRANSACTION, PAYMENT_METHOD, TRANSACTION_PAY_VAT, USER, TRANSACTION_PAY_SALES_TAX, ENTRY,

}
