ALTER TABLE ACCOUNT DROP COLUMN STRING_ID;

ALTER TABLE COMMODITY_CODE DROP COLUMN
STRING_ID;

ALTER TABLE ACCOUNT_TRANSACTION DROP COLUMN
STRING_ID;

ALTER TABLE FISCAL_YEAR DROP COLUMN
STRING_ID;

ALTER TABLE BANK DROP COLUMN
STRING_ID;

ALTER TABLE BUDGET DROP COLUMN
STRING_ID;

ALTER TABLE COMPANY DROP COLUMN
STRING_ID;

ALTER TABLE COMPANY_NOMINAL_CODE_RANGE DROP COLUMN
STRING_ID;
	
	
ALTER TABLE CREDITRATING DROP COLUMN
STRING_ID;

	
ALTER TABLE CURRENCY DROP COLUMN
STRING_ID;


ALTER TABLE CUSTOMER_GROUP DROP COLUMN
STRING_ID;	
	
ALTER TABLE ITEM DROP COLUMN
STRING_ID;	
	
ALTER TABLE TAX_ITEM_GROUPS DROP COLUMN
STRING_ID;	

	
ALTER TABLE ITEMGROUP DROP COLUMN
STRING_ID;	

ALTER TABLE PAYEE DROP COLUMN
STRING_ID;		
	
ALTER TABLE PAYMENTTERMS DROP COLUMN
STRING_ID;		

ALTER TABLE PRICELEVEL DROP COLUMN
STRING_ID;	

ALTER TABLE SHIPPINGMETHOD DROP COLUMN
STRING_ID;	
	
ALTER TABLE SHIPPINGTERMS DROP COLUMN
STRING_ID;		
	
ALTER TABLE TAXRATES DROP COLUMN
STRING_ID;		

ALTER TABLE TAX_RATE_CALCULATION DROP COLUMN
STRING_ID;	
	
ALTER TABLE ITEM_BACK_UP DROP COLUMN
STRING_ID;	

ALTER TABLE UNIT_OF_MEASURE COLUMN
STRING_ID;
	
	
ALTER TABLE USERS COLUMN
STRING_ID;

ALTER TABLE VENDOR_GROUP COLUMN
STRING_ID;	

ALTER TABLE FIXED_ASSET COLUMN
STRING_ID;		

ALTER TABLE DEPRECIATION COLUMN
STRING_ID;	
	
ALTER TABLE FIXED_ASSET_HISTORY COLUMN
STRING_ID;
	
ALTER TABLE FIXED_ASSET_NOTE COLUMN
STRING_ID;
	
	
ALTER TABLE VATRETURNBOX COLUMN
STRING_ID;
	
ALTER TABLE BOX COLUMN
STRING_ID;

ALTER TABLE TAX_CODE COLUMN
STRING_ID;

ALTER TABLE BRANDING_THEME COLUMN
STRING_ID;

ALTER TABLE TRANSACTION COLUMN
STRING_ID;	
	
	
ALTER TABLE ENTRY COLUMN
STRING_ID;		

ALTER TABLE CREDITS_AND_PAYMENTS COLUMN
STRING_ID;
	
ALTER TABLE TRANSACTION_MAKE_DEPOSIT COLUMN
STRING_ID;
	
	
ALTER TABLE TRANSACTION_PAYBILL COLUMN
STRING_ID;

ALTER TABLE TRANSACTION_RECEIVE_PAYMENT COLUMN
STRING_ID;
	
ALTER TABLE TRANSACTION_ISSUE_PAYMENT COLUMN
STRING_ID;	

ALTER TABLE TRANSACTION_PAY_SALES_TAX COLUMN
STRING_ID;	
	
ALTER TABLE TRANSACTION_PAY_VAT COLUMN
STRING_ID;	
	
ALTER TABLE TRANSACTION_RECEIVE_VAT COLUMN
STRING_ID;	
	
ALTER TABLE PAY_SALES_TAX_ENTRIES COLUMN
STRING_ID;	
	
	
ALTER TABLE PAY_VAT_ENTRIES COLUMN
STRING_ID;	

ALTER TABLE TRANSACTION_MAKE_DEPOSIT_ENTRIES COLUMN
STRING_ID;	
	
ALTER TABLE TRANSACTION_EXPENSE COLUMN
STRING_ID;	
	
ALTER TABLE TRANSACTION_PAY_EXPENSE COLUMN
STRING_ID;		
	


ALTER TABLE ITEM 
ADD COLUMN `MIN_STOCK_ALERT_LEVEL` int(11) default NULL,
ADD COLUNM `MAX_STOCK_ALERT_LEVEL` int(11) default NULL,
ADD  CONSTRAINT `FK227313CF909FD3` FOREIGN KEY (`MEASUREMENT`) REFERENCES `measurement` (`ID`);

ALTER TABLE USERS
ADD COLUMN `PASSWORD` varchar(255) default NULL,
ADD COLUMN `PHONE_NO` varchar(255) default NULL,
ADD COLUMN `COUNTRY_NAME` varchar(255) default NULL;


ALTER TABLE TRANSACTION_ITEM 
CHANGE COLUMN  `QUANTITY` `QTY_VALUE` double default NULL,
ADD CONSTRAINT `FK30714BF446AE6EF6` FOREIGN KEY (`QTY_UNIT`) REFERENCES `unit` (`ID`);


